### ISSUE TITLE
Dependency within NuGet is wrong for protobuf

### ISSUE THREAD

**Issue by boxhaxor** [SimonCropp/NServiceBus.ProtoBuf#1]
protobuf-net (≥ 2.0.0.688 && < 3.0.0)

However current version of protobuf is 2.0.0.668

I'm guessing this is a minor typo.  :)

**Comment by SimonCropp** [comment]
deployed

**Comment by boxhaxor** [comment]
Lightning fast!   Well done.

**Comment by SimonCropp** [comment]
FYI i have some proposed change in the licensing model for NuGet packages under the NServiceBusExtensions Org https://discuss.particular.net/t/proposed-change-in-the-licensing-model-for-nuget-packages-under-the-nservicebusextensions-org
